import Head from 'next/head'
import Header from "../Components/Header/Header";
import HeaderContainer from '../Components/HeaderContainer/HeaderContainer';
import Compare from '../Components/Compare/Compare';
import styles from '../styles/Home.module.css'
import Integration from '../Components/Integration/Integration';
import Compromise from '../Components/Compromise/Compromise';
import Success from '../Components/Success/Success';
import Resources from '../Components/Resources/Resources';
import Footer from '../Components/Footer/Footer';




export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>context Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Header></Header>
      <HeaderContainer />
      <Compare />
      <Integration />
      <Compromise />
      <Success />
      <Resources />
      <Footer />
      </main>
    </div>
  )
}
